CREATE DATABASE IF NOT EXISTS CONTROLE_FINANCEIRO;

USE CONTROLE_FINANCEIRO;

CREATE TABLE IF NOT EXISTS CATEGORIA_DESPESAS(
	CATEGORIA_DESPESAS_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS STATUS_DESPESAS(
	STATUS_DESPESAS_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS REFERENCIA_LANCAMENTO_DESPESAS(
	REFERENCIA_LANCAMENTO_DESPESAS_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	MES INTEGER NOT NULL,
	ANO INTEGER NOT NULL
);

CREATE TABLE LANCAMENTO_DESPESAS(
	LANCAMENTO_DESPESAS_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	CATEGORIA_DESPESAS_ID INTEGER NOT NULL,
	STATUS_DESPESAS_ID INTEGER NOT NULL,
	REFERENCIA_LANCAMENTO_DESPESAS_ID INTEGER NOT NULL,
	DESCRICAO VARCHAR(200) NOT NULL,
	VALOR FLOAT(18,2) NOT NULL,
	FOREIGN KEY (REFERENCIA_LANCAMENTO_DESPESAS_ID) REFERENCES REFERENCIA_LANCAMENTO_DESPESAS(REFERENCIA_LANCAMENTO_DESPESAS_ID),
	FOREIGN KEY (STATUS_DESPESAS_ID) REFERENCES STATUS_DESPESAS(STATUS_DESPESAS_ID),
	FOREIGN KEY (CATEGORIA_DESPESAS_ID) REFERENCES CATEGORIA_DESPESAS(CATEGORIA_DESPESAS_ID)
);

